steps:
- name: 'gcr.io/$PROJECT_ID/zip:latest'
  args: ['-r9T', 'build-$SHORT_SHA.zip', '.', '-x *node_modules*']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '-r', 'build-$SHORT_SHA.zip', 'gs://cb-deployment-893477233330']